app.schedule = [
  {
    name: 'Tutorial Day 1',
    date: 'Thursday, July 26th',
    sessions: [
      {
        track: [1],
        type: 'tutorial',
        name: 'Tutorial Session',
        speaker: 'TBD',
        start_time: '8:00am',
        end_time: '12:00pm',
        room: 'Salon C',
        description: '',
      },
      {
        track: [2],
        type: 'tutorial',
        name: 'Tutorial Session',
        speaker: 'TBD',
        start_time: '8:00am',
        end_time: '12:00pm',
        room: 'Salon D',
      },
      {
        solo: true,
        type: 'break',
        name: 'Lunch',
        speaker: 'TBD',
        start_time: '12:00pm',
        end_time: '1:00pm',
        room: 'Salon B + Michigan',
      },
      {
        track: [1],
        type: 'tutorial',
        name: 'Tutorial Session',
        speaker: 'TBD',
        start_time: '1:00pm',
        end_time: '5:00pm',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'tutorial',
        name: 'Tutorial Session',
        speaker: 'TBD',
        start_time: '1:00pm',
        end_time: '5:00pm',
        room: 'Salon D',
      },
    ],
  },
  {
    name: 'Conference Day 1',
    date: 'Friday, July 27th',
    sessions: [
      {
        solo: true,
        type: 'keynote',
        name: 'Welcome Keynote',
        speaker: 'TBD',
        start_time: '8:30am',
        end_time: '10:00am',
        room: 'Salon A/B',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '10:15am',
        end_time: '11:00am',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '10:15am',
        end_time: '11:00am',
        room: 'Salon D',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '11:15am',
        end_time: '12:00pm',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '11:15am',
        end_time: '12:00pm',
        room: 'Salon D',
      },
      {
        solo: true,
        type: 'break',
        name: 'Lunch',
        sponsor: 'TBD',
        start_time: '12:00pm',
        end_time: '1:00pm',
        room: 'Salon A/B + Michigan',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '1:30pm',
        end_time: '2:15pm',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '1:30pm',
        end_time: '2:15pm',
        room: 'Salon D',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '2:30pm',
        end_time: '3:15pm',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '2:30pm',
        end_time: '3:15pm',
        room: 'Salon D',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '3:30pm',
        end_time: '4:15pm',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '3:30pm',
        end_time: '4:15pm',
        room: 'Salon D',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '4:30pm',
        end_time: '5:15pm',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '4:30pm',
        end_time: '5:15pm',
        room: 'Salon D',
      },
      {
        solo: true,
        type: 'break',
        name: 'After Party',
        sponsor: 'TBD',
        start_time: '7:00pm',
        end_time: '9:00pm',
        room: 'TBD',
      },
    ],
  },
  {
    name: 'Conference Day 2',
    date: 'Saturday, July 28th',
    sessions: [
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '9:00am',
        end_time: '9:45am',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '9:00am',
        end_time: '9:45am',
        room: 'Salon D',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '10:00am',
        end_time: '10:45am',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '10:00am',
        end_time: '10:45am',
        room: 'Salon D',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '11:00am',
        end_time: '11:45am',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '11:00am',
        end_time: '11:45am',
        room: 'Salon D',
      },
      {
        solo: true,
        type: 'break',
        name: 'Lunch',
        sponsor: 'TBD',
        start_time: '12:00pm',
        end_time: '1:30pm',
        room: 'Salon A/B + Michigan',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '1:30pm',
        end_time: '2:15pm',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '1:30pm',
        end_time: '2:15pm',
        room: 'Salon D',
      },
      {
        track: [1],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '2:30pm',
        end_time: '3:15pm',
        room: 'Salon C',
      },
      {
        track: [2],
        type: 'session',
        name: 'Session',
        speaker: 'TBD',
        start_time: '2:30pm',
        end_time: '3:15pm',
        room: 'Salon D',
      },
      {
        solo: true,
        type: 'keynote',
        name: 'Closing Keynote',
        speaker: 'TBD',
        start_time: '3:30pm',
        end_time: '5:00pm',
        room: 'Salon A/B',
      },
    ],
  },
];
