app.sessions = [
  {
    track: [1],
    day: 1,
    type: 'tutorial',
    name: 'Docker for PHP Developers',
    speaker: 'christankersley',
    start_time: '8:00am',
    end_time: '12:00pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 1,
    type: 'tutorial',
    name: 'Hit the ground running with Laravel',
    speaker: 'joeferguson',
    start_time: '8:00am',
    end_time: '12:00pm',
    room: 'Salon D',
    description: '',
  },
  {
    solo: true,
    day: 1,
    type: 'break',
    name: 'Lunch',
    speaker: 'TBD',
    start_time: '12:00pm',
    end_time: '1:00pm',
    room: 'Salon B + Michigan',
    description: '',
  },
  {
    track: [1],
    day: 1,
    type: 'tutorial',
    name: 'Learn To Test Like A Grumpy Programmer',
    speaker: 'chrishartjes',
    start_time: '1:00pm',
    end_time: '5:00pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 1,
    type: 'tutorial',
    name: 'Dive into Symfony 4 & Flex!',
    speaker: 'ryanweaver',
    start_time: '1:00pm',
    end_time: '5:00pm',
    room: 'Salon D',
    description: '',
  },
  {
    solo: true,
    day: 2,
    type: 'keynote',
    name: 'Groupies, Roadies, Rockstars: The roles we play in opensource',
    speaker: 'calevans',
    start_time: '8:30am',
    end_time: '10:00am',
    room: 'Salon A/B',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '10:15am',
    end_time: '11:00am',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '10:15am',
    end_time: '11:00am',
    room: 'Salon D',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '11:15am',
    end_time: '12:00pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '11:15am',
    end_time: '12:00pm',
    room: 'Salon D',
    description: '',
  },
  {
    solo: true,
    day: 2,
    type: 'break',
    name: 'Lunch',
    sponsor: 'TBD',
    start_time: '12:00pm',
    end_time: '1:00pm',
    room: 'Salon A/B + Michigan',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '1:30pm',
    end_time: '2:15pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '1:30pm',
    end_time: '2:15pm',
    room: 'Salon D',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '2:30pm',
    end_time: '3:15pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '2:30pm',
    end_time: '3:15pm',
    room: 'Salon D',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '3:30pm',
    end_time: '4:15pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '3:30pm',
    end_time: '4:15pm',
    room: 'Salon D',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '4:30pm',
    end_time: '5:15pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '4:30pm',
    end_time: '5:15pm',
    room: 'Salon D',
    description: '',
  },
  {
    solo: true,
    day: 2,
    type: 'break',
    name: 'After Party',
    sponsor: 'TBD',
    start_time: '7:00pm',
    end_time: '9:00pm',
    room: 'TBD',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '9:00am',
    end_time: '9:45am',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '9:00am',
    end_time: '9:45am',
    room: 'Salon D',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '10:00am',
    end_time: '10:45am',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '10:00am',
    end_time: '10:45am',
    room: 'Salon D',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '11:00am',
    end_time: '11:45am',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '11:00am',
    end_time: '11:45am',
    room: 'Salon D',
    description: '',
  },
  {
    solo: true,
    day: 3,
    type: 'break',
    name: 'Lunch',
    sponsor: 'TBD',
    start_time: '12:00pm',
    end_time: '1:00pm',
    room: 'Salon A/B + Michigan',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '1:15pm',
    end_time: '2:00pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '1:15pm',
    end_time: '2:00pm',
    room: 'Salon D',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '2:15pm',
    end_time: '3:00pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '2:15pm',
    end_time: '3:00pm',
    room: 'Salon D',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '3:15pm',
    end_time: '4:00pm',
    room: 'Salon C',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Session',
    speaker: 'TBD',
    start_time: '3:15pm',
    end_time: '4:00pm',
    room: 'Salon D',
    description: '',
  },
  {
    solo: true,
    day: 3,
    type: 'keynote',
    name: 'I Community and So Can You',
    speaker: 'margaretstaples',
    start_time: '4:15pm',
    end_time: '5:30pm',
    room: 'Salon A/B',
    description: '',
  },
];
