app.sessions = [
  {
    solo: true,
    day: 1,
    type: 'break',
    name: 'Registration',
    speaker: 'TBD',
    start_time: '7:00am',
    end_time: '8:00am',
    room: 'Hallway',
    description: '',
  },
  {
    track: [1],
    day: 1,
    type: 'tutorial',
    name: 'Docker for PHP Developers',
    speaker: 'christankersley',
    start_time: '8:00am',
    end_time: '12:00pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 1,
    type: 'tutorial',
    name: 'Hit the ground running with Laravel',
    speaker: 'joeferguson',
    start_time: '8:00am',
    end_time: '12:00pm',
    room: 'Salon B',
    description: '',
  },
  {
    solo: true,
    day: 1,
    type: 'break',
    name: 'Lunch',
    speaker: 'TBD',
    start_time: '12:00pm',
    end_time: '1:00pm',
    room: 'Salon C + Michigan',
    description: '',
  },
  {
    track: [1],
    day: 1,
    type: 'tutorial',
    name: 'Learn To Test Like A Grumpy Programmer',
    speaker: 'chrishartjes',
    start_time: '1:00pm',
    end_time: '5:00pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 1,
    type: 'tutorial',
    name: 'Dive into Symfony 4 & Flex!',
    speaker: 'ryanweaver',
    start_time: '1:00pm',
    end_time: '5:00pm',
    room: 'Salon B',
    description: '',
  },
  {
    solo: true,
    day: 2,
    type: 'break',
    name: 'Registration',
    speaker: 'TBD',
    start_time: '7:00am',
    end_time: '8:30am',
    room: 'Hallway',
    description: '',
  },
  {
    solo: true,
    day: 2,
    type: 'keynote',
    name: 'Groupies, Roadies, Rockstars: The roles we play in opensource',
    speaker: 'calevans',
    start_time: '8:30am',
    end_time: '10:00am',
    room: 'Salon C/D',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Understanding Docker for Development',
    speaker: 'jessicamauerhan',
    start_time: '10:15am',
    end_time: '11:00am',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Building a Cloud-Friendly Application',
    speaker: 'larrygarfield',
    start_time: '10:15am',
    end_time: '11:00am',
    room: 'Salon B',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'MySQL 8 -- A New Beginning',
    speaker: 'davidstokes',
    start_time: '11:15am',
    end_time: '12:00pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Generators: All About the Yield',
    speaker: 'justinyost',
    start_time: '11:15am',
    end_time: '12:00pm',
    room: 'Salon B',
    description: '',
  },
  {
    solo: true,
    day: 2,
    type: 'break',
    name: 'Lunch',
    sponsor: 'TBD',
    start_time: '12:00pm',
    end_time: '1:00pm',
    room: 'Salon C/D + Michigan',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Lets Encrypt All The Things: HTTPS At Scale',
    speaker: 'philipsharp',
    start_time: '1:30pm',
    end_time: '2:15pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Dependency Injection For Mere Humans',
    speaker: 'ianlittman',
    start_time: '1:30pm',
    end_time: '2:15pm',
    room: 'Salon B',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'The Open Source Talk That Changed My Life Wasn\'t Technical',
    speaker: 'joeferguson',
    start_time: '2:30pm',
    end_time: '3:15pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: '20k Lines Under the C: A Guide to the PHP Startup Process and Hooking Absolutely Everything',
    speaker: 'joerozner',
    start_time: '2:30pm',
    end_time: '3:15pm',
    room: 'Salon B',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Database Theory and Modeling: A Crash Course',
    speaker: 'elizabethsmith',
    start_time: '3:30pm',
    end_time: '4:15pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Building a GraphQL API In PHP',
    speaker: 'andrewrota',
    start_time: '3:30pm',
    end_time: '4:15pm',
    room: 'Salon B',
    description: '',
  },
  {
    track: [1],
    day: 2,
    type: 'session',
    name: 'Greener Pastures: Infrastructure from the Ground Up',
    speaker: 'stevegrunwell',
    start_time: '4:30pm',
    end_time: '5:15pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 2,
    type: 'session',
    name: 'Webpack Encore: Pro JavaScript and CSS for Everyone!',
    speaker: 'ryanweaver',
    start_time: '4:30pm',
    end_time: '5:15pm',
    room: 'Salon B',
    description: '',
  },
  {
    solo: true,
    day: 2,
    type: 'break',
    name: 'After Party',
    sponsor: 'TBD',
    start_time: '7:00pm',
    end_time: '9:00pm',
    room: 'TBD',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'They are Watching You',
    speaker: 'christankersley',
    start_time: '9:00am',
    end_time: '9:45am',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'In 2018, PHPUnit isn\'t enough -- complementary tools for test-centric workflows',
    speaker: 'chrishartjes',
    start_time: '9:00am',
    end_time: '9:45am',
    room: 'Salon B',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Erasing the Stigma: Mental Health in Tech',
    speaker: 'jdflynn',
    start_time: '10:00am',
    end_time: '10:45am',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Managing Technical Debt',
    speaker: 'adamculp',
    start_time: '10:00am',
    end_time: '10:45am',
    room: 'Salon B',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Git: The Pain and the Gain',
    speaker: 'justinyost',
    start_time: '11:00am',
    end_time: '11:45am',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Building Your API for Longevity',
    speaker: 'mikestowe',
    start_time: '11:00am',
    end_time: '11:45am',
    room: 'Salon B',
    description: '',
  },
  {
    solo: true,
    day: 3,
    type: 'break',
    name: 'Lunch',
    sponsor: 'TBD',
    start_time: '12:00pm',
    end_time: '1:00pm',
    room: 'Salon C/D + Michigan',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'MySQL Without The SQL -- Oh My!',
    speaker: 'davidstokes',
    start_time: '1:15pm',
    end_time: '2:00pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'SOLID In Practice',
    speaker: 'jessicamauerhan',
    start_time: '1:15pm',
    end_time: '2:00pm',
    room: 'Salon B',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'The container is a lie!',
    speaker: 'larrygarfield',
    start_time: '2:15pm',
    end_time: '3:00pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Building for the PHP Command Line Interface',
    speaker: 'stevegrunwell',
    start_time: '2:15pm',
    end_time: '3:00pm',
    room: 'Salon B',
    description: '',
  },
  {
    track: [1],
    day: 3,
    type: 'session',
    name: 'Welcome to the Internet - We have packets!',
    speaker: 'elizabethsmith',
    start_time: '3:15pm',
    end_time: '4:00pm',
    room: 'Salon A',
    description: '',
  },
  {
    track: [2],
    day: 3,
    type: 'session',
    name: 'Load Testing Your App',
    speaker: 'ianlittman',
    start_time: '3:15pm',
    end_time: '4:00pm',
    room: 'Salon B',
    description: '',
  },
  {
    solo: true,
    day: 3,
    type: 'keynote',
    name: 'I Community and So Can You',
    speaker: 'margaretstaples',
    start_time: '4:15pm',
    end_time: '5:30pm',
    room: 'Salon C/D',
    description: '',
  },
];

app.sessions.forEach((session, idx) => {
  if (session.name === 'TBD' || !['keynote', 'tutorial', 'session'].includes(session.type)) {
    return;
  }

  let ident = session.name.replace(/[^0-9a-z]/gmi, '').toLowerCase()
  app.util.loadFile(`/assets/md/sessions/${session.speaker}/${ident}.md`, (data) => {
    app.sessions[idx].description = data.responseText
  })
})
